In [1]:
import pandas as pd

df = pd.read_csv("loan_data.csv")
df.head(10)

,applicant_id,name,age,income,credit_score,loan_amount,employment_status,married,gender,approved
0,APP1170,Raj Smith,NaN,"$66,400",NaN,89100.0,Unemployed,No,Female,Rejected
1,APP1177,Omar Silva,25.0,"$75,700",645.0,228600.0,Employed,NaN,Male,Approved
2,APP1132,Mei Khan,24.0,"$26,400",580.0,5000.0,employed,Yes,Female,Approved
3,APP1193,Liam Ali,28.0,"$78,500",NaN,272600.0,Employed,No,Female,Approved
4,APP1102,Raj Kumar,35.0,NaN,573.0,159000.0,employed,N,Female,Rejected
5,APP1182,Raj Silva,26.0,"$12,000",574.0,78000.0,Unemployed,Y,Male,Rejected
6,APP1189,Liam Smith,37.0,"$63,200",692.0,5000.0,employed,Yes,male,Approved
7,APP1073,Sara Brown,NaN,"$104,000",784.0,170200.0,employed,no,Male,Approved
8,APP1051,John Smith,56.0,"$60,500",780.0,182400.0,employed,Y,M,Approved
9,APP1185,Nina Silva,23.0,"$76,700",NaN,13700.0,Employed,Yes,F,Approved

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   applicant_id       212 non-null    object
 1   name               212 non-null    object
 2   age                194 non-null    float64
 3   income             202 non-null    object
 4   credit_score       195 non-null    float64
 5   loan_amount        212 non-null    float64
 6   employment_status  201 non-null    object
 7   married            200 non-null    object
 8   gender             202 non-null    object
 9   approved           212 non-null    object
dtypes: float64(3), object(7)
memory usage: 16.7+ KB

In [3]:
df.describe()

              age  credit_score    loan_amount
count  194.000000    195.000000     212.000000
mean    43.448454    648.574359  152261.792453
std     20.945523    132.753971   85665.271670
min     -5.000000      0.000000    5000.000000
25%     31.000000    582.500000   88950.000000
50%     41.000000    652.000000  155800.000000
75%     54.000000    737.500000  207575.000000
max    200.000000    850.000000  448800.000000

In [4]:
df.shape

(212, 10)

In [5]:
df.isna().sum()

applicant_id          0
name                  0
age                  18
income               10
credit_score         17
loan_amount           0
employment_status    11
married              12
gender               10
approved              0
dtype: int64

In [6]:
df.head(3)

,applicant_id,name,age,income,credit_score,loan_amount,employment_status,married,gender,approved
0,APP1170,Raj Smith,NaN,"$66,400",NaN,89100.0,Unemployed,No,Female,Rejected
1,APP1177,Omar Silva,25.0,"$75,700",645.0,228600.0,Employed,NaN,Male,Approved
2,APP1132,Mei Khan,24.0,"$26,400",580.0,5000.0,employed,Yes,Female,Approved

In [7]:
df = df.drop(columns=["applicant_id", "name"])
df.head(3)

,age,income,credit_score,loan_amount,employment_status,married,gender,approved
0,NaN,"$66,400",NaN,89100.0,Unemployed,No,Female,Rejected
1,25.0,"$75,700",645.0,228600.0,Employed,NaN,Male,Approved
2,24.0,"$26,400",580.0,5000.0,employed,Yes,Female,Approved

In [8]:
before = df.shape[0]
df = df.drop_duplicates()
after = df.shape[0]
print(f"before: {before}, after: {after}")

before: 212, after: 200

In [9]:
df['income'] = (
    df['income'].astype(str)
      .str.replace(r'[$,]', '', regex=True)   # remove $ and commas
      .str.strip()
)
df.head(3)

,age,income,credit_score,loan_amount,employment_status,married,gender,approved
0,NaN,66400,NaN,89100.0,Unemployed,No,Female,Rejected
1,25.0,75700,645.0,228600.0,Employed,NaN,Male,Approved
2,24.0,26400,580.0,5000.0,employed,Yes,Female,Approved

In [10]:
df['income'] = pd.to_numeric(df['income'], errors='coerce')
df.head(3)

,age,income,credit_score,loan_amount,employment_status,married,gender,approved
0,NaN,66400.0,NaN,89100.0,Unemployed,No,Female,Rejected
1,25.0,75700.0,645.0,228600.0,Employed,NaN,Male,Approved
2,24.0,26400.0,580.0,5000.0,employed,Yes,Female,Approved

In [11]:
df['gender'] = df['gender'].astype(str).str.strip().str.lower().map(
    {'male': 'Male', 'm': 'Male', 'female': 'Female', 'f': 'Female'}
)

In [12]:
df.gender.value_counts()

gender
Male      102
Female     88
Name: count, dtype: int64

In [13]:
df['married'] = df['married'].astype(str).str.strip().str.lower().map(
    {'yes': 'Yes', 'y': 'Yes', 'no': 'No', 'n': 'No'}
)

In [14]:
df.married.value_counts()

married
Yes    114
No      76
Name: count, dtype: int64

In [15]:
emp_map = {
    'employed': 'Employed',
    'self employed': 'Self-Employed', 'self-employed': 'Self-Employed',
    'unemployed': 'Unemployed',
}
df['employment_status'] = df['employment_status'].astype(str).str.strip().str.lower().map(emp_map)

df.employment_status.value_counts()

employment_status
Employed         110
Self-Employed     48
Unemployed        32
Name: count, dtype: int64

In [16]:
import numpy as np
df.loc[(df['age'] < 18) | (df['age'] > 100), 'age'] = np.nan
df.describe()

              age         income  credit_score    loan_amount
count  180.000000     188.000000    184.000000     200.000000
mean    42.327778   52789.361702    645.951087  151629.500000
std     12.861458   21143.955119    134.420646   86473.742375
min     21.000000   12000.000000      0.000000    5000.000000
25%     31.000000   37925.000000    581.500000   88250.000000
50%     41.000000   51150.000000    656.000000  157450.000000
75%     54.000000   68325.000000    729.250000  205700.000000
max     64.000000  104000.000000    850.000000  448800.000000

In [17]:
df.loc[(df['credit_score'] < 300) | (df['credit_score'] > 850), 'credit_score'] = np.nan
df.describe()

              age         income  credit_score    loan_amount
count  180.000000     188.000000    180.000000     200.000000
mean    42.327778   52789.361702    660.288889  151629.500000
std     12.861458   21143.955119     94.675836   86473.742375
min     21.000000   12000.000000    425.000000    5000.000000
25%     31.000000   37925.000000    584.000000   88250.000000
50%     41.000000   51150.000000    665.500000  157450.000000
75%     54.000000   68325.000000    731.750000  205700.000000
max     64.000000  104000.000000    850.000000  448800.000000

In [18]:
df.isna().sum()

age                  20
income               12
credit_score         20
loan_amount           0
employment_status    10
married              10
gender               10
approved              0
dtype: int64

In [20]:
num_cols = ['age', 'income', 'credit_score', 'loan_amount']

for c in num_cols:
    df[c] = df[c].fillna(df[c].median())

df.isna().sum()

age                   0
income                0
credit_score          0
loan_amount           0
employment_status    10
married              10
gender               10
approved              0
dtype: int64

In [23]:
df.employment_status.mode()

0    Employed
Name: employment_status, dtype: object

In [24]:
for c in ['gender', 'employment_status', 'married']:
    df[c] = df[c].fillna(df[c].mode()[0])

df.isna().sum()

age                  0
income               0
credit_score         0
loan_amount          0
employment_status    0
married              0
gender               0
approved             0
dtype: int64

In [25]:
df.head()

,age,income,credit_score,loan_amount,employment_status,married,gender,approved
0,41.0,66400.0,665.5,89100.0,Unemployed,No,Female,Rejected
1,25.0,75700.0,645.0,228600.0,Employed,Yes,Male,Approved
2,24.0,26400.0,580.0,5000.0,Employed,Yes,Female,Approved
3,28.0,78500.0,665.5,272600.0,Employed,No,Female,Approved
4,35.0,51150.0,573.0,159000.0,Employed,No,Female,Rejected

In [26]:
df['approved'] = df['approved'].map({'Approved': 1, 'Rejected': 0})
df.head()

,age,income,credit_score,loan_amount,employment_status,married,gender,approved
0,41.0,66400.0,665.5,89100.0,Unemployed,No,Female,0
1,25.0,75700.0,645.0,228600.0,Employed,Yes,Male,1
2,24.0,26400.0,580.0,5000.0,Employed,Yes,Female,1
3,28.0,78500.0,665.5,272600.0,Employed,No,Female,1
4,35.0,51150.0,573.0,159000.0,Employed,No,Female,0

In [27]:
df = pd.get_dummies(df, columns=['gender', 'employment_status', 'married'], drop_first=True)
df.head()

,age,income,credit_score,loan_amount,approved,gender_Male,employment_status_Self-Employed,employment_status_Unemployed,married_Yes
0,41.0,66400.0,665.5,89100.0,0,False,False,True,False
1,25.0,75700.0,645.0,228600.0,1,True,False,False,True
2,24.0,26400.0,580.0,5000.0,1,False,False,False,True
3,28.0,78500.0,665.5,272600.0,1,False,False,False,False
4,35.0,51150.0,573.0,159000.0,0,False,False,False,False

In [29]:
df[num_cols]

      age    income  credit_score  loan_amount
0    41.0   66400.0         665.5      89100.0
1    25.0   75700.0         645.0     228600.0
2    24.0   26400.0         580.0       5000.0
3    28.0   78500.0         665.5     272600.0
4    35.0   51150.0         573.0     159000.0
..    ...       ...           ...          ...
206  34.0   28800.0         665.5     162900.0
208  54.0  103000.0         818.0      89900.0
209  55.0   64600.0         688.0      47600.0
210  30.0   40500.0         669.0     290300.0
211  41.0   61200.0         505.0     251200.0

[200 rows x 4 columns]

In [30]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])
df[num_cols].head()

        age    income  credit_score  loan_amount
0 -0.098160  0.670402      0.052355    -0.724918
1 -1.412433  1.125193     -0.176488     0.892336
2 -1.494575 -1.285690     -0.902087    -1.699909
3 -1.166007  1.262119      0.052355     1.402438
4 -0.591012 -0.075358     -0.980228     0.085448

In [31]:
df[num_cols].describe()

                age        income  credit_score   loan_amount
count  2.000000e+02  2.000000e+02  2.000000e+02  2.000000e+02
mean  -3.108624e-17 -8.881784e-18  5.995204e-16 -1.998401e-17
std    1.002509e+00  1.002509e+00  1.002509e+00  1.002509e+00
min   -1.741001e+00 -1.989883e+00 -2.632361e+00 -1.699909e+00
25%   -7.552964e-01 -6.805243e-01 -7.569670e-01 -7.347727e-01
50%   -9.815978e-02 -7.535844e-02  5.235474e-02  6.747836e-02
75%    8.054031e-01  6.483955e-01  7.388828e-01  6.268514e-01
max    1.791108e+00  2.509128e+00  2.111939e+00  3.445164e+00

In [32]:
df.head()

,age,income,credit_score,loan_amount,approved,gender_Male,employment_status_Self-Employed,employment_status_Unemployed,married_Yes
0,-0.098160,0.670402,0.052355,-0.724918,0,False,False,True,False
1,-1.412433,1.125193,-0.176488,0.892336,1,True,False,False,True
2,-1.494575,-1.285690,-0.902087,-1.699909,1,False,False,False,True
3,-1.166007,1.262119,0.052355,1.402438,1,False,False,False,False
4,-0.591012,-0.075358,-0.980228,0.085448,0,False,False,False,False

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X = df.drop(columns=['approved'])
y = df['approved']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

print(f"Test accuracy: {model.score(X_test, y_test):.2f}")

Test accuracy: 0.75

In [40]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.78      0.78      0.78        23
           1       0.71      0.71      0.71        17

    accuracy                           0.75        40
   macro avg       0.74      0.74      0.74        40
weighted avg       0.75      0.75      0.75        40